/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_qing_mvpart_demo_MainActivity */

#ifndef _Included_com_qing_mvpart_demo_MainActivity
#define _Included_com_qing_mvpart_demo_MainActivity
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     com_qing_mvpart_demo_MainActivity
 * Method:    stringFromJNI
 * Signature: ()Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_com_qing_mvpart_demo_MainActivity_stringFromJNI
  (JNIEnv *, jobject);

#ifdef __cplusplus
}
#endif
#endif
